[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "avsRAG"
version = "0.1.0"

[project.scripts]
avsrag = "cli.run:main"

[tool.hatch.build.targets.wheel]
packages = ["cli"]