[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "avsRAG"
version = "0.1.0"

[project.scripts]
# key = "module.path:callable"
avsrag = "cli.run:main"

[tool.setuptools.packages.find]
include = ["cli"]